первое ревью
DinaraBack/hotelBooking pull request #1
Opened 2024-12-16 15:32 UTC by DinaraBack

Я не могу назначить ревьюера, но дала доступ к репозиторию

2024-12-16 16:27 UTC, alex13slem requested changes

2024-12-16 16:27 UTC, alex13slem commented on src/booking/booking.controller.ts
> +    async create(@Body() bookingData: any) {
Почему не сделали dto и не провалидировали входные данные?

2024-12-16 16:27 UTC, alex13slem commented on src/room/room.controller.ts
> +    async create(@Body() roomData: any) {
Ведь есть dto - почему не использовали?

2024-12-17 10:07 UTC, DinaraBack commented on src/booking/booking.controller.ts
> +    async create(@Body() bookingData: any) {
исправила

2024-12-17 10:07 UTC, DinaraBack commented on src/room/room.controller.ts
> +    async create(@Body() roomData: any) {
исправила

2024-12-23 18:22 UTC, alex13slem requested changes

2024-12-23 18:22 UTC, alex13slem commented on src/room/room.controller.ts
> +    async update(@Param('id') id: string, @Body() roomData: CreateRoomDto) {
На create и на update должны быть разные dto, id например менять нельзя, при этом остальные филды должны меняться выборочно.

2024-12-23 18:22 UTC, alex13slem commented on src/booking/booking.controller.ts
> +    async create(@Body(new ValidationPipe()) bookingData: CreateBookingDto) {
Рекомендуется использовать глобальный пайп.

2025-01-09 09:22 UTC, alex13slem approved these changes

2025-01-14 12:55 UTC, AlariCode commented
./dist надо исключить в gitignore

2025-01-14 12:58 UTC, AlariCode commented on src/room/dto/create-room.dto.ts
> +    view?: string;  // Дополнительная характеристика, например, вид на море (необязательное поле)
Наверное вид на море может принимать значение только true и false

2025-01-14 12:58 UTC, AlariCode commented on src/booking/dto/create-booking.dto.ts
> +    status: 'active' | 'cancelled';
'active' | 'cancelled' лучше всего вынести в Enum

2025-01-17 15:36 UTC, merged